# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51f0e829992a9d9fb2996dcc164a1770fca6d7e02a6afee5fafdf9b11a9eff4c39cbeaae69dacfc2c06ff259f9ddc16567ada3d6a14aa214fac39946e265d1b7

test:
  secret_key_base: 91ba02a59a128b7439330c337d6702975bd2856423b2823c62d110087eb39b42203e0fe4aec96a28d54693e567493a87d86179ce4e58834ee99fba3ce19eba69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
